version: '3.5'

services:

  service_container:
    container_name: account_service_container
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env 

    ports:
      - ${GRPC_PORT}:${GRPC_PORT}

    depends_on:
      
       postgres:
          condition: service_healthy
    
            
      
  postgres:
    container_name: account2_postgres
    image: postgres
    env_file:
      - .env  
    environment:
      POSTGRES_DB: ${PG_DATABASE}

      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}  
      PGDATA: /var/lib/postgresql/data
    ports:
      - ${PG_PORT}:5432
    
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DATABASE}" ]
      interval: 10s
      timeout: 5s
      retries: 3


    restart: unless-stopped
    volumes:
      - postgres_data:/data/postgres


  redis:
    image: "redis:alpine"
    command: redis-server --requirepass ${REDIS_PASS}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - ./redis-data:/var/lib/redis
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master

networks:
  default:
    external:
      name: shared-net
            
      
volumes:
  postgres_data: